import type { Metadata } from "next";
import "@/f_shared/atoms/globals.css";
import { Inter } from "next/font/google";
import { ReactQueryClient } from "@/f_shared/atoms";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<DefaultChildren_Props>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClient>{children}</ReactQueryClient>
      </body>
    </html>
  );
}
